version: "3"

services:
  web:
    container_name: exampleCompose
    restart: always
    build: .
    ports:
      - "5000:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: dbCompose
    image: mongo
    ports:
      - "27018:27017"
